### ISSUE TITLE
Google Code is shutting down

### ISSUE THREAD

**Issue by ajlanghorn** [JordanHatch/situation-room#1]
This project references dependencies hosted on Google Code, which is shutting down. Thankfully, the projects concerned all appear to have been moved to GitHub. In all but one case, I think things will continue running fine - the use of the OAuth2 dependency will need a bit of work, I think, because it looks like something's changed upstream.

I'll have a play and push a branch when I've got something concrete.

**Comment by JordanHatch** [comment]
@ajlanghorn I missed this comment - apologies. I would consider this application no longer maintained, in favour of [the new meeting-rooms app](https://github.com/JordanHatch/meeting-rooms).

**Comment by ajlanghorn** [comment]
👍👍

On Tuesday, 19 January 2016, Jordan Hatch notifications@github.com wrote:

> @ajlanghorn https://github.com/ajlanghorn I missed this comment -
> apologies. I would consider this application no longer maintained, in
> favour of the new meeting-rooms app
> https://github.com/JordanHatch/meeting-rooms.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JordanHatch/situation-room/issues/1#issuecomment-173006919
> .

## 

Sent on the move
